name: Build .exe

on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: windows-latest

        steps:
            -   name: Checkout repo
                uses: actions/checkout@v2
            
            -   name: Setup Python
                uses: actions/setup-python@v2
                with:
                    python-version: '3.12'

            -   name: Install dependencies
                run: |
                sudo apt update
                sudo apt-get install -y qtbase5-dev qt5-qmake libxcb-xinerama0
                pip install -r requirements.txt
                pip install pyinstaller

            -   name: Build .exe
                run: |
                pyinstaller --onedir --windowed --add-data "styles/styles.qss;styles" --add-data "config.env;." --add-data "default_settings.py;." main.py

            -   name: Move .exe to repo root
                run: |
                move dist]main\main.exe .\main.exe

            -   name: Upload .exe to GitHub
                uses: actions/upload-artifact@v2
                with:
                    name: latest-exe
                    path: main.exe